### ISSUE TITLE
Your experience

### ISSUE THREAD

**Issue by LaurieJohnston** [JudicialAppointmentsCommission/digital-platform#101]

**Comment by LaurieJohnston** [comment]
Your experience

List your employment history, including any judicial appointments, starting with your most recent job

< Button - Add job >

< Show Q1 - repeatable >

< Q1 >

Title
< Text input > 

Required field
Validation error: Enter the job title

From
Month < 2 character box >
Year < 4 character box >  

Required field
Validation error: Enter the month and year that you started this appointment
Validation error: The dates must be in the past

I currently work in this job
< Checkbox > 

To
Month < 2 character box >
Year < 4 character box >


< If this is a present job, use the present tense in all questions below. Otherwise use past. >


Present tense: Is this job a judicial appointment?
Past tense: Was this job a judicial appointment?

< radio buttons >

Yes < show Q1a >
No < show Q1b >

Required field
Validation error: Select yes or no


< Q1a >

Present tense: Is the appointment salaried or fee-paid? 
Past tense: Was the appointment salaried or fee-paid?

< Radio buttons > 

Salaried
Fee-paid

Required field
Validation error: Select salaried or fee-paid


Present tense: What’s your jurisdiction?
Past tense: What was your jurisdiction?

< Text input - short answer > 

Required field
Validation error: Enter the jurisdiction


Present tense: Which circuit do you work on?
Present tense: Which circuit did you work on?

< Radio buttons > 
London and south east
Western
Midlands
Northern 
North eastern 
Wales 

Required field
Validation error: Select the circuit 


Present tense: Which region do you work in? 
Present tense: Which region did you work in? 

< Text input - short answer >

Required field
Validation error: Enter the region 


Present tense: How many days have you sat in this appointment?
Present tense: How many days did you sit in this appointment?


< Text input >

Required field
Validation error: Enter the number of days

< Secondary button - Remove job >
< Primary button - Add job >


< Q1b >

Is this job in the Government Legal Service or Crown Prosecution Service?

 < radio buttons >

Yes < FIND OUT IF THIS AFFECTS JOURNEY >
No

Required field
Validation error: Select yes or no


Company or organisation
< Text input >

Required field
Validation error: Enter the company or organisation

Present tense: What law-related activities do you do?
Past tense: What law-related activities did you do?

Select all that apply

< Checkboxes >
Carrying out of judicial functions of any court or tribunals
Acting as an arbitrator
Practising or being employed as a lawyer
Advising (whether or not in the course of such practice or employment as a lawyer) on the application of the law
Assisting (whether or not in the course of such practice) persons involved in proceedings for the resolution of issues arising under the law
Acting (whether or not in the course of such practice) as a mediator in connection with attempts to resolve issues that are the subject of proceedings or could be, if not resolved
Drafting (whether or not in the course of such practice) documents intended to affect persons’ rights and obligations  
Teaching or researching law
Other

< When user selects ‘Other’ show text input - short answer >

Required field
Validation error: Select all law-related activities that apply

Main duties
< Text input - short answer >

Required field
Validation error: Enter your main duties

Specialism/s
< Text input - short answer >

Required field
Validation error: Enter any specialism/s

< Secondary button - Remove job >
< Primary button - Add job >




Q2 Have you had any gaps in employment since you qualified?

< Radio buttons > 
Yes < show Q2a >
No

Required field
Validation error: Select yes or no


Q2a What law-related activities did you do during this time, if any?
Select all that apply

< Checkboxes >
Carrying out of judicial functions of any court or tribunals
Acting as an arbitrator
Practising or being employed as a lawyer
Advising (whether or not in the course of such practice or employment as a lawyer) on the application of the law
Assisting (whether or not in the course of such practice) persons involved in proceedings for the resolution of issues arising under the law
Acting (whether or not in the course of such practice) as a mediator in connection with attempts to resolve issues that are the subject of proceedings or could be, if not resolved
Drafting (whether or not in the course of such practice) documents intended to affect persons’ rights and obligations  
Teaching or researching law
Other

< When a user selects a box show text input - short answer below checkbox >

Required field
Validation error: Select all law-related activities that apply


< Q3 - repeatable> 

Have you had any work published?

< Radio buttons > 
Yes < show Q3a >
No

Required field
Validation error: Select yes or no


< Q3a >
 
Title
< Text input >

Date
For example, 02 2017

Month < 2 character box >
Year < 4 character box >


< Secondary button - Remove publication >
< Primary button - Add publication >


< Q4 - repeatable >

Are you a member of any legal associations?
< Radio buttons >
 
Yes < show Q4a >
No

Required field
Validation error: Select yes or no

Q4a

Legal association
< Text input >

< Secondary button - Remove association>
< Secondary button - Add association>


< Button - Save and continue >
< Button - Save draft >

**Comment by ollietreend** [comment]
Wireframe in root of [Strategy drive](https://drive.google.com/drive/folders/0AEuYk50Pr3MaUk9PVA) as 'Your experience.pdf'
