### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by NoraJAC** [JudicialAppointmentsCommission/digital-platform#104]
I want to monitor form usage and drop-out rates

So I can understand how users are using the form

**Comment by tatyree** [comment]
I've created a new property for this.  The tracking tag is:

```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-104899914-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-104899914-3');
</script>
```

**Comment by tatyree** [comment]
We need to do some additional work to track single-page app clicks.  That should be done via the google tag manager dashboard.  I'll raise a separate ticket fo that shortly.
