### ISSUE TITLE
Media questions

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/digital-platform#106]
We need to capture where the candidate saw the vacancy so we can review our channels of communication

**Comment by ClaireTroughtonJAC** [comment]
##How did you hear about the vacancy?

Q1: Select all that apply:
[Check boxes]

JAC Website
Professional body website or email (eg The Law Society)
Professional body magazine
Judicial Office Extranet
Twitter
LinkedIn
Word of mouth
I prefer not to answer this question
Other form of communication (text box - short answer)


Q2 Is this your first application for a judicial post?
[Radio buttons]
Yes
No [show Q3]
I prefer not to answer this question

Q3If ‘No’ please indicate how many times:
[Radio buttons]
Once 
Twice 
Three times 
More than three

**Comment by NoraJAC** [comment]
##How did you hear about the vacancy?

Q1: Select any that apply:
[Check boxes]

JAC website
JAC newsletter: Judging Your Future
Judiciary intranet
Judiciary extranet
Twitter
LinkedIn
Word of mouth
I prefer not to answer this question
Other form of communication (text box - short answer)
