### ISSUE TITLE
Reasonable length of service

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#115]
As a selection exercise manager, I need to ascertain if an applicant meets the additional selection criteria (ASC) in relation to their reasonable length of service.

I want to ask them this question as set out below:

There is no upper or lower age limit for candidates apart from the statutory retirement age of 70. However, the age at which someone is appointed as a judicial office holder must allow for a reasonable length of service before retirement. For this role it is usually 3 years. 

If you already hold judicial appointment and were first appointed before March 1995, you may have a preserved retirement age of 72. This includes if you were first appointed to a judicial office listed in Schedule 7 to the Judicial Pensions and Retirement Act 1993.

Please indicate whether you meet the reasonable length of service of 3 years.

Yes 
No - Q1A

Q1A. If you cannot provide a reasonable length of service of 3 years, please provide any mitigation you would like the Commission to consider.
<Short text box - 250 words>

**Comment by sme-JAC** [comment]
This came to light on Tuesday 5th March.  Is snagging as well as this will be added to Your Self Assessment.

**Comment by LaurieJohnston** [comment]
We could ask it as - 
If you were successful in this role, could you commit to at least 5 years' service?
Yes / No

< If no >
Tell us why you couldn't commit to at least 5 years' service

**Comment by CbarkerJAC** [comment]
Hi Laurie,  Policy team have reviewed. Your suggestion is fundamentally incorrect because the RLS wording relates to the statutory retirement age. Please could we go with Jonathan's form of words?
