### ISSUE TITLE
Self assessment editorial amends

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#131]
On left hand navigation, please change to:
Self-assessment
On page title, please change to: Your self-assessment and ASC

Change Additional Selection Criteria to: Additional selection criteria

Next to the question, add: (up to 250 words)

Self Assessment, change sub heading to: Self-assessment

Please amend wording under self-assessment to: Please refer to the guidance and competency framework on the JAC website before completing this part of your application.

Beside each competency, please insert: (up to 250 words)

Question, in addition to the 250 word limit mentioned, can there be a word count down displayed for applicants to see.

Please add Leadership competence following the guidance above.

**Comment by CbarkerJAC** [comment]
Please change 'Additional Selection Criteria' to 'Additional Selection **Criterion**'

This is because there is only 1 ASC for this exercise and multiple ASC is Criteria. A single ASC is criterion. I apologise but, please check that Nora agrees before amending.

**Comment by NoraJAC** [comment]
This ticket has moved to close but the amends don't appear to have been made, so moving back to To do

**Comment by tatyree** [comment]
Closed originally because it's a duplicate.  @ClaireTroughtonJAC to review in the morning.
