### ISSUE TITLE
Assessors editorial amends

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#132]
Please change page title to: Assessors 

Under Your assessors, please change: Two to 2, and link sentence to:
https://www.judicialappointments.gov.uk/references-guidance-candidates

Can the assessor boxes have a number against them, so the "this" is relative to the number 1 or 2.

**Comment by CbarkerJAC** [comment]
Following policy's review of this page we would like the functionality built to be able to add  a 'Personal' assessor as another kind of assessor. This is not urgent.

**Comment by ollietreend** [comment]
Closing as won't fix.
