### ISSUE TITLE
Character editorial amends

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#133]
Change page title to: Character

Under motoring offences > endorsements. Delete the word: "Ordered" in the question.

Under insolvency and debt > question 2. Change "enter" to: "entered"

Under insolvency and debt > question 4. Change "date" in answer box to: "Date of insolvency".

Under VAT and tax > question 2. Change been "penalised" to: "received a penalty."

Under current investigation or proceedings, Change question to: "Are you subject to any current investigations or proceeding."

Following comment applies to all date fields.
Please could the year start at 1960.

In all questions: Please insert additional date field under "offence text" box in every question.

**Comment by CbarkerJAC** [comment]
Policy have reviewed this page and have the following comments:

**1)** Policy agrees with inserting an additional date field under offence text box in every question (Date: Month / Year)

**Comment by CbarkerJAC** [comment]
Following on from my comment above policy would like the question below to stand alone like the 'Current investigations or proceedings' question. It does not have to have a sub-heading. It is not part of the 'Professional conduct' section. 

Is there anything else that is relevant to your character that you haven't already told us?
For example, anything which might make a member of the public think you're unsuitable for this post

**Comment by CbarkerJAC** [comment]
I'm sorry but I also forgot to say that we would like the question above to move to the very last question.
