### ISSUE TITLE
Diversity editorial amends

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#135]
Selection of DO NOT share my diversity data, the questions asked in you may share my data should still appear.

Please add these paragraphs before applicants agree or not to us sharing their data:
 
### Diversity
The JAC will use the information that you provide in 2 ways:
1.	where the Equal Merit Provision policy applies
2.	to monitor the selection process
To find out more information please click the link:
[Link to website: https://www.judicialappointments.gov.uk/providing-diversity-information-jac]

Under Sharing my diversity data. Change MoJ to: Ministry of Justice; and HMCTS to HM Courts and Tribunals Service

As per ticket 45, please replace the questions with the following:

https://docs.google.com/document/d/1sHrhkWldpi7hxKBVl_A4X9EgM7lma-Bwboqjdp8xPl0/edit 

1.    Sharing my diversity data
       You may share my diversity data with the Ministry of Justice, Judicial Office and HM Courts and Tribunals Service (for monitoring purposes only)
       Do NOT share my diversity data
[***both options should allow the user to fill in the form****]

2.    What is your professional background? Select all that apply
        - [ ] Barrister
         - [ ] CILEx
         - [ ] Solicitor
         - [ ] Other (please specify)
         - [ ] Prefer not to answer

3.    What is your current legal role? If you currently hold multiple roles, select all that apply
        - [ ] Academic
         - [ ] Barrister
         - [ ] Fee-paid court judge
         - [ ] Fee-paid tribunal judge
         - [ ]  Fellow of CILEx
          - [ ] Other fee-paid judicial office holder
          - [ ] Other salaried judicial office holder
         - [ ] Salaried court judge
         - [ ] Salaried tribunal judge
         - [ ]  Solicitor
         - [ ] Other (please specify
         - [ ] Prefer not to answer

4.  Do you hold, or have you held in the past, a fee-paid judicial role?
    - [ ] Fee-paid court post
    - [ ] Fee-paid tribunal post
    - [ ] I have not previously held a fee-paid role
    - [ ] Other fee-paid judicial office\
    - [ ] Prefer not to answer

5.  Between the ages 11 to 18, did you mainly attend a state or fee-paying school?
- [ ] UK state school – selective
- [ ] UK state school – non-selective
- [ ] UK independent or fee-paying school
- [ ] UK independent or fee-paying school with financial assistance (bursary or means-tested scholarship)
 - [ ] I attended a school outside of the UK
 - [ ] Prefer not to answer

6.    Did you go to university and if so, were you the first generation from your family to go?
- [ ]    I did not go to university
- [ ] I went to university and was the first generation in my family to do so
- [ ] I went to university but was not first generation in my family to do so
- [ ]   Prefer not to answer

7.    What is your ethnic group?

Asian/Asian British
- [ ] Bangladeshi
- [ ] Chinese
- [ ]  Indian
- [ ] Pakistani
- [ ] Any other Asian background

Black/ African/ Caribbean/ Black British
- [ ] African
- [ ]Caribbean
- [ ] Any other Black/ African/ Caribbean background

White
- [ ] English, Welsh, Scottish, Northern Irish, British
- [ ] Irish
- [ ] Gypsy or Irish Traveller
- [ ] Any other White background

Mixed or multiple ethnic backgrounds
- [ ] White and Black Caribbean
- [ ] White and Black African
- [ ] White and Asian
- [ ] Any other mixed or multiple ethnic background

Other ethnic group
- [Other text box]

8.    What is your gender?
  - [ ]  Female
  - [ ]  Male    
  - [ ]  Other
  - [ ]  Prefer not to answer
 
9. Is your gender identity the same as the gender you were assigned at birth?
     - [ ]  Yes
      - [ ]  No
       - [ ]  Prefer not to answer

10.  How would you describe your sexual orientation?
     - [ ] Bisexual
      - [ ] Gay man
       - [ ] Gay woman/ lesbian
        - [ ] Heterosexual/ straight
         - [ ] Other
           - [ ] Prefer not to answer

11.  Do you have a disability, as defined by the Equality Act 2010?
     - [ ]   Yes
      - [ ]  No
       - [ ]  Prefer not to answer

12.   What is your religion or belief?
           - [ ]  Atheist
           - [ ] Buddhist
           - [ ]  Christian
           - [ ]  Hindu
           - [ ] Jewish
          - [ ]  Muslim
           - [ ] No religion
            - [ ] Sikh
            - [ ] Other
            - [ ] Prefer not to answer

13. Have you attended an outreach event on JAC selection exercises?
         - [ ]  Yes
          - [ ] No
          - [ ]  Prefer not to answer

14.   Did you participate in a Judicial Work Shadowing Scheme?
         - [ ] Yes
           - [ ]  No
           - [ ] Prefer not to answer

Please make all of the questions mandatory.

**Comment by NoraJAC** [comment]
Richard has approved these questions. While it's to go to the Commissioners tomorrow, I do not expect change. Please proceed with implementing this version!
