### ISSUE TITLE
Citizenship editorial amends

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#137]
Change page title and left hand navigation from Nationality to: Citizenship

What is your citizenship?

I am a citizen of the United Kingdom
I am a citizen of the Republic of Ireland
I am a citizen of another Commonwealth country
I am none of these

-[If user selects 'I'm none of these' show]
Email dcj128@judicialappointments.gov.uk to provide further details.

**Comment by ollietreend** [comment]
Are we making a conscious decision to switch from the more informal "I'm" to "I am"?
