### ISSUE TITLE
Personal details editorial amends

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#138]
Change to" Name" Field

In the field help text please add "We will use this name when contacting your assessors."

This page has over use of capitals.
Capitalisation should only be on the first word, with the following exceptions:

Please check:  that "National Insurance number" is displayed like this.  

Other changes to Content

Under "Your name" in two placed, "e.g." should be spelt as For example:

In "Your contact details", please change "regarding your application" to read "about your application."

Question, should all fields be compulsory?

Under Your Date of Birth
The year starts at 0, please can it start at 1950.

---

Requires JudicialAppointmentsCommission/application-form#45
Requires JudicialAppointmentsCommission/application-form#46
Requires JudicialAppointmentsCommission/application-form#47
Requires JudicialAppointmentsCommission/digital-platform#145

**Comment by ollietreend** [comment]
> Under Your Date of Birth
> The year starts at 0, please can it start at 1950.

Validation is not being performed on this field for MVP.

**Comment by ollietreend** [comment]
@ClaireTroughtonJAC do the changes to Reasonable Adjustments in this card (as well as in #145) supersede those proposed by @LaurieJohnston in #28?

https://github.com/JudicialAppointmentsCommission/digital-platform/issues/28#issuecomment-465437057

The proposal was to change the wording and section heading from 'Reasonable Adjustments' to 'Your health'

**Comment by ClaireTroughtonJAC** [comment]
@ollietreend For MVP we are sticking with reasonable adjustments and this does supercede ticket #28 and therefore we closed it.
