### ISSUE TITLE
Qualification editorial amends

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#139]
Please change page title by removing the word Your, so it should be: Qualifications

Please change the question What are you qualified as, to read: 
Are you qualified as a:
Barrister
Solicitor
Advocate

Under Qualification date, the year starts at 0, please can it start at 1960.

Under When were you called to the Bar, the year starts at 0, please can it start at 1960.

Amend the email address for sending the pupillage certificate to DCJ128@judicialappointments.gov.uk

On 'Your Qualifications' page, could you change the question 'When were you admitted as a solicitor?' to 'When were you entered on the Roll?'.  Could you then remove the question 'Are you currently on the Roll?'
 
Please can the year start at 1960, as it currently starts at 0.

**Comment by ClaireTroughtonJAC** [comment]
Comment from Todd:  

Depend on JudicialAppointmentsCommission/digital-platform#76

On 'Your Qualifications' page, could you change the question 'When were you admitted as a solictor?' to 'When were you entered on the Roll?'.

Could you then remove the question 'Are you currently on the Roll?'. You do not have to currently be on the Roll to be eligible.

**Comment by ClaireTroughtonJAC** [comment]
Please change page title by removing the word Your, so it should be Qualifications

Please change the question What are you qualified as, to read Are you qualified as a:
Barrister
Solicitor
Allow candidate to choose both options

Please change the question where did you qualify?, to Did you qualify in England and Wales?
Yes
No
If No, bring up a prompt to contact the JAC, along the same wording as Citizenship prompt.

Under Qualification date, the year starts at 0, please can it start at 1960.

Under When were you called to the Bar, the year starts at 0, please can it start at 1960.

For Solicitor, When were you entered onto the roll (currently reads when were you admitted as a solicitor, see Todds comment above), please can the year start at 1960, as it currently starts at 0.

**Comment by ollietreend** [comment]
- > Under Qualification date, the year starts at 0, please can it start at 1960.
- > Under When were you called to the Bar, the year starts at 0, please can it start at 1960.
- > Please can the year start at 1960, as it currently starts at 0.

No field input validation is in place for MVP.

**Comment by ollietreend** [comment]
> Please change the question What are you qualified as, to read:
> Are you qualified as a:
> Barrister
> Solicitor
> Advocate
> 
> Please change the question where did you qualify?, to:
> Did you qualify in England and Wales?
> Yes
> No

Is this correct, since an advocate can only qualify in Scotland?

**Comment by ClaireTroughtonJAC** [comment]
@ollietreend There has been some confusion on this ticket.  I've amended the description to remove the amendments to the second question.  Essentially I shouldn't have included Advocate and Scotland in the MVP but its too late to remove it now.  Please just make an amendment to the first question as shown in the description.  I missed this point when reviewing the ticket.
