### ISSUE TITLE
Content for sign-up and log-in page/s

### ISSUE THREAD

**Issue by NoraJAC** [JudicialAppointmentsCommission/digital-platform#143]
On the Sign up page please add the following text before the login box: 

To apply for this role you will now need to create an account with your email address and a password. You will  then receive an email to verify your account details to login.

If you’re already registered, login to see your application.

**Comment by NoraJAC** [comment]
Needs JAC logo in landscape version (Todd has a copy of this I think)

<h1>Application for Senior Circuit Judge, Designated Civil Judge </h1>

<p>To apply for this role you will need to create an account with your email address and a password. You will receive an email to verify your account details to login </p>

<p>If you’re already registered, login to see your application</p>

**Comment by ollietreend** [comment]
@ClaireTroughtonJAC need some thinking around how to explain to users that this is not their JARS account. Also the login form isn't necessarily vacancy-specific (although we only have one vacancy in the form for now)
