### ISSUE TITLE
Self assessment amendment

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#144]
Amendments:  

Please change the order of the fields so that the Self Assessment text boxes are at the top of the page ahead of the Additional Selection Criterion and Section 9(1) Authorisations.  

Self- Assessment, change sub heading to: Self-assessment
Under the sub-heading Self-Assessment . Please amend wording under self-assessment to: Please refer to the guidance and competency framework (https://www.judicialappointments.gov.uk/sites/default/files/sync/128_final_competency_framework.pdf) on the JAC website before completing this part of your application.  Please add an additional sentence after "part of your application" to say "You have a maximum of 250 words for each competency".  

Please add an additional long text box for the "Leadership" competence at the top of the other competencies.  

Please amend "Working and Communicating with others" to: "Working and Communicating with Others."

Please change 'Additional Selection Criteria' to 'Additional Selection Criterion'

Next to the question about Additional Selection Criterion please add a text box titled "Please provide details": (Text box - long answer - up to 250 words)

Above Section 9(1) Authorisation please add new heading:

Reasonable Length of Service
Refer to the Information Page.

 If you are unable to provide 3 years service please provide any mitigation you would like the Commission to consider.
<Short text box - 250 words>

**Comment by ollietreend** [comment]
Having tested the textareas with 250 words, I've made them bigger to be more comfortable when typing in. They were previously 3 lines tall, now they're 9.

**Comment by ollietreend** [comment]
I'd suggest the 'reasonable length of service' question is restructured into two questions, to follow the pattern we've followed elsewhere in the form:

"Are you able to provide 3 years' service?"
Yes / No

If the user says 'No', follow up with:

"Provide any mitigation you'd like considered"
[ textbox]

**Comment by ClaireTroughtonJAC** [comment]
@ollietreend  I agree the amendments above.

**Comment by ollietreend** [comment]
### Additional Selection Criterion

Remove 2nd 'please provide details' textarea
Change label of first question to read: "Provide details of how you meet this requirement"

**Comment by ClaireTroughtonJAC** [comment]
Link to Information Page  https://www.judicialappointments.gov.uk/128-senior-circuit-judge-designated-civil-judge-information-page 
Please change disabled candidates to candidates with a disability.
