### ISSUE TITLE
Preferences amendments

### ISSUE THREAD

**Issue by sme-JAC** [JudicialAppointmentsCommission/digital-platform#150]
Related to https://github.com/JudicialAppointmentsCommission/digital-platform/issues/59

Preferences tab.
1. Change the title from "Your Preferences" to "Preferences". 
2. Change question from: "Do you want to work part-time?" to:
"Are you interested in salaried part-time working?"

if candidate chooses "yes". Box appears "What sitting patterns are you interested in?":
Option list will come up: delete "block of weeks"

**Comment by tatyree** [comment]
Doing this at the same time I am setting up the Preferences part of the Review and Submit page.
