### ISSUE TITLE
Character Amendments

### ISSUE THREAD

**Issue by sme-JAC** [JudicialAppointmentsCommission/digital-platform#151]
Change the title from "Your character" to "Character".
For motoring and criminal offences if you click "yes". 
Under offence add date field.
Month Year.

Under professional conduct move the question:
"Is there anything else that is relevant to your character that you haven't already told us?"

We would like this moved to the end and as a stand alone question.
Please title this:
Additional Information

**Comment by ollietreend** [comment]
For 'offence' repeatable section, fields should be:

1. Offence
2. Date of offence
3. Sentence or penalty
4. Date of sentence or penalty
5. Circumstances

"Is there anything else that is relevant to your character that you haven't already told us?" – move to its own fieldset with heading 'Additional information'
