### ISSUE TITLE
Monitor the state of the Notify job

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/digital-platform#162]

**Comment by ClaireTroughtonJAC** [comment]
Transcript of Slack conversation

However, it doesn't re-send emails to bad addresses.  It might re-send temporary bounces.

 Does that mean if a candidate types the wrong email we would advise them to start again as it is unlikely that they will get another email?


Right now we'll have to detect it by looking for errors in the Notify console.  We can monitor the state of the Notify job in a later iteration.

Until we do that, the platform won't know the email is bad.

**Comment by tatyree** [comment]
Make a dashboard user for Notify that only has permissions to see dashboard.
