### ISSUE TITLE
Use GOV.UK Notify for outgoing emails

### ISSUE THREAD

**Issue by ollietreend** [JudicialAppointmentsCommission/digital-platform#20]
required by #51
required by #54

The GOV.UK Notify service can be used to send transactional notification emails. This is the standard service to use in government for sending emails – it's managed by GDS, and is free for use by central government.

This can replace SendGrid to provide a reliable, but free, email service.

Likely notification emails we'll need:

- Application submitted notification
- Changes in application status
- Invitations to assessment days
- Independent Assessment requests
- etc. (This list is not exhaustive)

**Comment by tatyree** [comment]
Needs to check with Nora on this.

**Comment by tatyree** [comment]
I've just messaged GDS about getting `judicialappointments.digital` added to the list of approved domains.  I put @ClaireTroughtonJAC and Head of Comms down as being able to confirm the request.

**Comment by tatyree** [comment]
GDS have added the domain and I've set up Notify in trial mode:

https://www.notifications.service.gov.uk/services/0abe6c8e-0b87-4cde-9493-5da4921ccc53
