### ISSUE TITLE
Login / register page

### ISSUE THREAD

**Issue by sme-JAC** [JudicialAppointmentsCommission/digital-platform#22]
1. Candidate must have the ability to log on via a link/ button that will take the candidate to a page to create a new account. 
2. Candidate reads about the role from the information page, either a link or button to bring up the start of the application form. 
3. This link must have the Option to save/ remember candidate if they chose to log out and save their progress.

**Comment by sme-JAC** [comment]
Possible duplicate of #107

**Comment by JonSJAC** [comment]
User experience, when a user first clicks on the link to apply, there should be two options.

1 Sign in

Enter email address

Enter password

2 Create account

Enter email address

Create password

Verify email address

**Comment by NoraJAC** [comment]
this ticket is superceded by #143
