### ISSUE TITLE
Nationality

### ISSUE THREAD

**Issue by sme-JAC** [JudicialAppointmentsCommission/digital-platform#30]
Statutory Requirement, needs to be in the application somewhere
You need to be a citizen of: 
•	the United Kingdom, or
•	another Commonwealth country, or
•	the Republic of Ireland

**Comment by LaurieJohnston** [comment]
What’s your nationality?

[[what about dual nationality - does it make a difference?]]

<img width="851" alt="nationality question" src="https://user-images.githubusercontent.com/47528637/53041751-ad530900-347c-11e9-91e2-de6d700f516a.png">

<Radio buttons> 
British 
including English, Scottish, Welsh and Northern Irish
Irish
Citizen of a Commonwealth country
Citizen of a different country

If user selects ‘Citizen of a Commonwealth country’ reveal
Name of Commonwealth country 
<Dropdown>

Required field
Validation error: Select if you are British, Irish, a citizen of a Commonwealth country or a citizen of a different country

<img width="847" alt="nationality error" src="https://user-images.githubusercontent.com/47528637/53041790-bd6ae880-347c-11e9-9ee2-47d088fe9388.png">

**Comment by LaurieJohnston** [comment]
Check if dual nationality makes any difference - do we need to say 'If you have dual nationality, select any option that is relevant to you'?

Need error message for 'Name of Commonwealth country' dropdown

What is the messaging around eligibility / ineligibility?
How do we stop users going any further?

**Comment by ClaireTroughtonJAC** [comment]
The important point here is that to be eligible for a Judicial Appointment you must be:
A citizen of:
United Kingdom
Republic of Ireland
A Commonwealth country

**Comment by LaurieJohnston** [comment]
**What's your nationality?** 

<Radio buttons> 

- British (including English, Scottish, Welsh and Northern Irish)
- Irish
- I'm a citizen of a Commonwealth country
- None of these

If user selects 'None of these' show
Call 020 3334 0123 to discuss your application

**Comment by NoraJAC** [comment]
Suggest we change title to Citizenship, which is more accurate, and consistent with what is on the information page.

So ask: What is your citizenship?

**Comment by LaurieJohnston** [comment]
Change heading to 'Citizenship'
Change question to 'What's your citizenship'
Change first 2 radio buttons to 'I'm a UK citizen' and 'I'm an Irish citizen'

It might be a good idea to add this type of component - to say 'Help with citizenship'
<img width="853" alt="screenshot 2019-03-01 at 11 11 16" src="https://user-images.githubusercontent.com/47528637/53634811-21c34000-3c13-11e9-8911-d67a798be889.png">
@NoraJAC Is this a good idea and would you be able to draft some content for it?

**Comment by sme-JAC** [comment]
Nora to define Republic of Ireland
Laurie looking for feedback about definition of citizenship

**Comment by NoraJAC** [comment]
What is your citizenship?

I am a citizen of the United Kingdom
I am a citizen of the Republic of Ireland
I am a citizen of another Commonwealth country
I am none of these

-[If user selects ‘I am a citizen of another Commonwealth country’]
Text box: Please state which country

-[If user selects 'I'm none of these' show]
Email dcj128@judicialappointments.gov.uk or call 020 3334 0123 to discuss your application

I suggest not including definition of nationality because it’s clear what the eligibility requires and it’s 3 categories (that is, not complex). 

To capture the information about citizenship of the Commonwealth, I’ve suggested a text box, but do not consider this MVP.
