### ISSUE TITLE
Legal experience

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#40]

**Comment by JonSJAC** [comment]
1.	Candidates need to be able to present the dates of their legal experience in an easier way, just need month and year. Needs to then work out the time engaged in this activity automatically so candidate doesn’t have to do this manually.
2.	Candidate needs the ability to add multiple experiences categories of law through A-I to be discussed and explained to developers. (Examples of A-I are stored in the Google Drive).

**Comment by JonSJAC** [comment]
3.	IMPORTANT this needs to sit better with regards to duplicating data in career history. Can the candidate have the option to somehow easily inter change with what they have already entered in their career history? 
4.	At this stage can this also be used to flag the candidate’s eligibility.

**Comment by ClaireTroughtonJAC** [comment]
Todd please tidy.  In relation to ticket 42.

**Comment by tatyree** [comment]
I'm taking myself off of this ticket for now as @LaurieJohnston is working on the content design and the workflow may well change as a result.

**Comment by LaurieJohnston** [comment]
Closing because covered by 76
