### ISSUE TITLE
Personal Details - Master Ticket

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#42]
The candidate is required to complete all fields in this ticket. 

## Done when
The following fields are available on the form and save their information to the database:
- [ ] Professional surname
- [ ] Surname
- [ ] Forenames
- [ ] Title
- [ ] Suffix
- [ ] DOB
- [ ] NINO (National Insurance Number)
- [ ] Candidates address
- [ ] Telephone phone number
- [ ] Email address
- [ ] Reasonable Adjustments* see ticket #28

This page will include the subsection Education* see ticket 29.  This ticket is not dependent on completion of this.  

Data Validation - TBD.

**Comment by tatyree** [comment]
Information from ticket #23 regarding title and suffix: 
Title e.g Mr etc (dropdown box with different options)
Suffix e.g OBE, MBE, QC, CBE, Other (Brings up text box) (dropdown box with options)

Given that this isn't heavy in detail, just follow lists from the existing system for now.

**Comment by ollietreend** [comment]
Following the [GDS guidelines around asking for names](https://design-system.service.gov.uk/patterns/names/), I'm asking for the applicant's full legal name, and a preferred name for information communications (2 fields).

This simplifies upon the originally proposed 5 fields for collecting the user's name (Professional Surname, Surname, Forenames, Title, Suffix).

We will need to provide evidence to support asking for the applicant's name in a more granular (& complex) fashion if this is required.

**Comment by ClaireTroughtonJAC** [comment]
Nationality
We need to determine what is the most important question.  
1)Are they a citizen of UK, RoI or commonwealth?  If commonwealth what country
or 
2) What is your nationality?  

1) This confirms what JAC needs to know to determine a candidate's eligibility for a judicial post.  
2) Is not something we necessarily need to determine eligibility.

We need to show Laurie fields that Ollie is considering

**Comment by ClaireTroughtonJAC** [comment]
Names discussion

Assumption:  We do not need 5 boxes to capture this information.  

Challenge is:  JAC has always separate Forename and Surname for processing candidate through the exercise, addressing emails and presenting and sharing information.  

This does not conform to GDS in the sense that we are not asking candidates things in the simplest way.  However to do it this way requires more changes to process - but this is not insurmountable.

**Comment by LaurieJohnston** [comment]
Change wording on National Insurance question to 'It's on your National Insurance card, payslip or P60' 
We can't say DWP or HMRC letter as that's not something that everyone has whereas the other examples are generic. Think these 3 are enough anyway

**Comment by ClaireTroughtonJAC** [comment]
Review this item to make it an Epic and possibly close this card and make smaller cards in an epic

**Comment by sme-JAC** [comment]
Laurie and Ollie to review.

**Comment by ollietreend** [comment]
Closing as remaining work has been split into separate cards:

#84
JudicialAppointmentsCommission/application-form#45

**Comment by tatyree** [comment]
I'm closing this ticket for now as this all seems to be contained in other tickets now.

**Comment by JonSJAC** [comment]
This page has over use of capitals.
Capitalisation should only be on the first word, with the following exceptions:

National Insurance number

Content

Under Your name in two placed, e.g. should be spelt as For example:

In Your contact details, please change regarding your application to read about your application.

Reasonable Adjustments:

Please change disabled candidates to candidates with a disability.

Question, should all fields be compulsory?

Under Your Date of Birth
The year starts at 0, please can it start at 1950.
