### ISSUE TITLE
Career History

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#43]
## Background

Candidates need to be able to compile their complete career history and judicial appointments history so that it can be collected at the start of each exercise

We would like this displayed in personal details.

## Done When
The following sub-sections and fields are available and saved to the database.

### Field Title 
Job Title
Company name
Date* MM/YYYY to MM/YYYY
Text Box Description of duties* add word limit, 250 words.
Area of specialism.
We would like candidates to be told to enter their career history in order of most recent job first, then going backwards over a 10 year period. *If it is possible, we would like the data to auto sort chronologically.
Button with the option to add multiple jobs.

### Career Break
Yes No tick box, if no move on, if yes.
If Yes Date box appears.
Text box brief explanation of career break. Word limit to be discussed (400)
 

 If they select a Judicial appointment, we need the following data to be captured:

## Field titles
Salaried, Fee paid, candidates should be able to select both options..
Candidate enters the following details:
Job Title
Dates* MM/YYYY to MM/YYYY
Jurisdiction
Circuit or Region
Number of sitting days

For both options:  Candidates should be prompted to enter these in date order, starting with the most recent. 

Thinking about future updates of this information, if possible, we would like the dates to auto sort, if candidates enter data that is not in date order.

Legal experience subsection, this is about the Candidate's eligibility:  
What is your current legal role?
Other fields specified in ticket 40.  
This needs to be built but is not mutually independent.

**Comment by LaurieJohnston** [comment]
Closing because covered by 76
