### ISSUE TITLE
Candidate Eligibility

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/digital-platform#44]
As a candidate
I want to be able to confirm if I am eligible for this post before I apply
so that I know whether I should proceed.  

Quiz to ask: 
Nationality
Post Qualification experience 5 or 7 years etc

If the response for both is yes - recommend to proceed.  

If any response for the questions is no - recommend that they may not be eligible. 

If they proceed to application in any event

## Field titles
Nationality

**Comment by LaurieJohnston** [comment]
Closing because this is covered by 30
