### ISSUE TITLE
Email validation on user registration

### ISSUE THREAD

**Issue by ollietreend** [JudicialAppointmentsCommission/digital-platform#51]
Users should validate their email address whilst registering to use the application form.

The flow could look something like:

- User registers on Application Form login page
- User is authenticated to the application, but until `emailVerified` becomes `true`, user sees a message asking them to verify their email.
- Upon clicking the link which gets emailed to them, user is re-authenticated with `emailVerified` and allowed to access the rest of the Application Form.

Other things to think about:

- Can we change the wording or styling of the Firebase verification email?
- Ideally we want to use GOV.UK Notify for verification emails – can we do this?
- Can we use email verification URLs which map to our app domain name? (They are currently firebase.com URLs)
- Ideally they'll look and feel consistent with other notification emails sent from the application (e.g. application received confirmation email)

**Comment by tatyree** [comment]
While I'm waiting for the GDS response mentioned in #20, I'm going to work on getting a tested firebase function working using sendgrid.  Depending on how far I get, I can then swap out the sendgrid api call for the gov.uk notify one.
