### ISSUE TITLE
Candidate Eligibility - Master

### ISSUE THREAD

**Issue by JonSJAC** [JudicialAppointmentsCommission/digital-platform#52]
depends on #43

As a candidate
I want to be able to provide details of how I meet the statutory eligibility.
As a member of staff, I want the system to assess whether candidates satisfy the statutory eligibility requirements.

(Post Qualification experience 7 years)

Please see ticket 40

## Field titles

Professional role * drop down with list of options, Barrister or Solicitor, must be able to select both.

Subject to above answer.
Candidate is presented with the following options:

Solicitor:

Date entered onto roll.

Barrister:

Date completed pupillage, or were granted an exemption. IF granted exemption, JAC staff need to see the certificate. System must allow for the candidate to upload, either by word/pdf/jpeg.

Please note: This ticket IS dependant on ticket 43 being completed. Part of the eligibility, revolves around the candidates career history.

**Comment by LaurieJohnston** [comment]
Closing because covered by 30
