### ISSUE TITLE
Email Confirmation

### ISSUE THREAD

**Issue by sme-JAC** [JudicialAppointmentsCommission/digital-platform#54]
## Background

The candidate need to have an acknowledgement email confirming their application has been submitted/received. 

## Done when
~~Nora provides wording~~
~~We can add a survey link separate from the copy~~
 - [ ] A trackable email is sent from the system when the user submits their application.

**Comment by tatyree** [comment]
Suggested wording probably looks something like: 

The outcomes will be out on dd/mm. If successful interviews will be held on dd/mm, In London...
Thank you for your application.  You can access your application here.
Please take a moment to help us improve our service by taking our brief survey here.

**Comment by tatyree** [comment]
I'm starting this one while waiting on GDS to put us live.  I've invited Nora to notify, and will give her a run through of how to edit the templates the next time we're both in the office together.

**Comment by ollietreend** [comment]
Email should include a link to the Google Form for participant research recruitment (tagging @LaurieJohnston)

**Comment by tatyree** [comment]
I've linked in @JonSJAC's ticket with the copy.
