### ISSUE TITLE
Your qualifications

### ISSUE THREAD

**Issue by LaurieJohnston** [JudicialAppointmentsCommission/digital-platform#76]

**Comment by LaurieJohnston** [comment]
Your experience

List your employment history, starting with your most recent job or judicial appointment

<Button - Add job>

<Show Q1>

Q1 Is this job a judicial appointment?

<radio buttons>

Yes <show Q1a>
No <show Q2>

Required field
Validation error: Select yes or no

Q1a Is this appointment current or past?

<Radio buttons> 

Current <show Q1b>
Past <show Q1i>

Required field
Validation error: Select current or past


Q1b What’s your job title?

<Text input - short answer> 

Required field
Validation error: Enter the job title


Q1c Is the appointment salaried or fee-paid? 

<Radio buttons> 

Salaried <show Q1d>
Fee-paid <show Q1d>

Required field
Validation error: Select whether the appointment is salaried or fee-paid


Q1d What’s your jurisdiction?

<Text input - short answer> 

<show Q1e>

Required field
Validation error: Enter the jurisdiction


Q1e When did you start the appointment?
For example, 02 2017

Month <2 character box>
Year <4 character box>  

<show Q1f>

Required field
Validation error: Enter the month and year that you started this appointment
Validation error: The dates must be in the past



Q1f Which circuit do you currently work on?

<Radio buttons> 
London and south east <show Q1g>
Western <show Q1g>
Midlands <show Q1g>
Northern <show Q1g>
North eastern <show Q1g>
Wales <show Q1g>

Required field
Validation error: Select the circuit you work on


Q1g Which region do you currently work in? 

<Text input - short answer>

<show Q1h>

Required field
Validation error: Enter the region you work in


Q1h How many days have you sat in this current appointment?

<Text input>

Required field
Validation error: Enter the number of days

<Secondary button - Remove job>
<Primary button - Add job>


Q1i What was your job title?

<Text input - short answer> 

Required field
Validation error: Enter the job title


Q1j Was this appointment salaried or fee-paid? 

<Radio buttons> 

Salaried <show Q1k>
Fee-paid <show Q1k>

Required field
Validation error: Select whether the appointment was salaried or fee-paid


Q1k What was your jurisdiction?

<Text input - short answer> 

<show Q1l>


Required field
Validation error: Enter the jurisdiction


Q1l When did you start the appointment?
For example, 02 2017

Month <2 character box>
Year <4 character box>  

<show Q1m>

Required field
Validation error: Enter the month and year that you started this appointment
Validation error: The dates must be in the past



Q1m What circuit did you work on?

<Radio buttons> 
London and south east <show Q1n>
Western <show Q1n>
Midlands <show Q1n>
Northern <show Q1n>
North eastern <show Q1n>
Wales <show Q1n>

Required field
Validation error: Select the circuit you worked on


Q1n Which region did you work in? 

<Text input - short answer>

<show Q1o>

Required field
Validation error: Enter the region you worked in

Q1o How many days did you sit in this appointment?

<Text input>

Required field
Validation error: Enter the number of days


<Secondary button - Remove job>
<Primary button - Add job>


Q2 Is this job in the Government Legal Service or Crown Prosecution Service?
 <radio buttons>

Yes <show Q2a>
No <show Q2a>

Required field
Validation error: Select yes or no


Q2a

From
For example, 06 2016

Month <2 character box>
Year <4 character box>

To
For example, 02 2019

Month <2 character box>
Year <4 character box>

Required field
Validation error: Enter from and to dates
Validation error: The dates must be in the past

No end date
<check box>

Job title
<Text input>

Required field
Validation error: Enter the job title

Company or organisation
<Text input>

Required field
Validation error: Enter the company or organisation

Law-related activities
Select all that apply

<Checkboxes>
Carrying out of judicial functions of any court or tribunals
Acting as an arbitrator
Practising or being employed as a lawyer
Advising (whether or not in the course of such practice or employment as a lawyer) on the application of the law
Assisting (whether or not in the course of such practice) persons involved in proceedings for the resolution of issues arising under the law
Acting (whether or not in the course of such practice) as a mediator in connection with attempts to resolve issues that are the subject of proceedings or could be, if not resolved
Drafting (whether or not in the course of such practice) documents intended to affect persons’ rights and obligations  
Teaching or researching law
Other

<When a user selects ‘Other’ show text input - short answer>

Required field
Validation error: Select all law-related activities that apply

Main duties
< Text input - short answer>

Required field
Validation error: Enter your main duties

Specialism/s
< Text input - short answer>

Required field
Validation error: Enter any specialism/s

<Secondary button - Remove job>
<Primary button - Add job>


Q3 Have you had any gaps in employment since you qualified?

<Radio buttons> 
Yes <show Q3a>
No

Required field
Validation error: Select yes or no


Q3a What law-related activities did you do during this time, if any?
Select all that apply

<Checkboxes>
Carrying out of judicial functions of any court or tribunals
Acting as an arbitrator
Practising or being employed as a lawyer
Advising (whether or not in the course of such practice or employment as a lawyer) on the application of the law
Assisting (whether or not in the course of such practice) persons involved in proceedings for the resolution of issues arising under the law
Acting (whether or not in the course of such practice) as a mediator in connection with attempts to resolve issues that are the subject of proceedings or could be, if not resolved
Drafting (whether or not in the course of such practice) documents intended to affect persons’ rights and obligations  
Teaching or researching law
Other

<When a user selects a box show text input - short answer below checkbox>
Required field
Validation error: Select all law-related activities that apply


Q4 Have you had any work published?

<Radio buttons> 
Yes <show Q4a>
No

Required field
Validation error: Select yes or no

Q4a
 
Title
<Text input>

Date
For example, 02 2017

Month <2 character box>
Year <4 character box>


<Secondary button - Remove publication>
<Primary button - Add publication>


Q5 Are you a member of any legal associations?
<Radio buttons>
 
Yes <show Q5a>
No

Required field
Validation error: Select yes or no

Q5a

Legal association
<Text input>

<Secondary button - Remove association>
<Secondary button - Add association>


<Button - Save and continue>
<Button - Save draft>

**Comment by ollietreend** [comment]
To make question logic simpler for now, I've made Q2 'Are you?' a radio input so users can only select one option. This may need some discussion, as I'm not sure it works with Q2 accepting multiple and Q2a only accepting one answer.

**Comment by ollietreend** [comment]
Discussed with @ClaireTroughtonJAC and confirmed that we're okay to make Q2 and Q2a both radio buttons (to only accept one response). This is fine for MVP.

**Comment by kaspatel** [comment]
Need to remove  'An advocate' and 'Scotland' and 'Northern Ireland' as the possible options as  only Solicitors and Barristers in England and Wales are eligible for this exercise.

**Comment by CbarkerJAC** [comment]
Re Kas' comment above, alternatively you could add 'CILEx.

**Comment by CbarkerJAC** [comment]
Following the policy review of the onlie app platform we would like to request the following:

On 'Your Qualifications' page, could you change the question 'When were you admitted as a solictor?' to 'When were you entered on the Roll?'. 

Could you then remove the question 'Are you currently on the Roll?'. You do not have to currently be on the Roll to be eligible.

**Comment by tatyree** [comment]
I've now broken out @CbarkerJAC's request into it's own snagging ticket (https://github.com/JudicialAppointmentsCommission/application-form/issues/52).  Closing this one.
