### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by LaurieJohnston** [JudicialAppointmentsCommission/digital-platform#84]

**Comment by LaurieJohnston** [comment]
# Your name

Q1 **Full professional name**
We'll use this name when contacting you about your application
<Text input>

Q2 **Are you or have you been known by any other name?**
We need this to do a character check
<Radio buttons> 
Yes <show text input>
No

**Comment by ollietreend** [comment]
@LaurieJohnston does anything else need to happen after the 'yes/no' on Q2? i.e. do we need to show another field, as we do with 'Other (please specify)' responses in lists?

**Comment by LaurieJohnston** [comment]
@ollietreend Yes, exactly.
