### ISSUE TITLE
Your Character 

### ISSUE THREAD

**Issue by sme-JAC** [JudicialAppointmentsCommission/digital-platform#91]
As a candidate
I want to declare anything that would reflect poorly on my character
so that it can be considering me for a judicial appointment
These are potentially multiple entry fields.
Candidate can add additional information at a later date without editing the original information submitted. Unlike the rest of the application this is the only section you can do this.

Done when 
The following subsections and fields are available and save to the database:

Q1 
Have you ever been convicted of, cautioned for or received a conditional caution for a motoring offence (other than a parking offence)?
< radio buttons >
Yes < show Q1a >
No

Q1a

Offence
< text input >

Sentence or penalty
< text input >

Month
< date input >
Year
< date input >

Circumstances
Give any circumstances you want to be taken into account when we consider your application
< text input - short answer >

Remove
< button >

Add another
< button >

Q2 Have you ever received a penalty notice?
< radio buttons >
Yes < show Q1a >
No

Q3
Have you received any fixed penalty notices in the past 4 years?
< radio buttons >
Yes < show Q1a >
No

Q4 Have you received any endorsements ordered on your licence in the past 4 years? 
< radio buttons >
Yes < show Q1a >
No

Q5 Have you ever been convicted of or cautioned for a criminal offence? 
< radio buttons >
Yes < show Q1a >
No

Q6 Have you ever been declared bankrupt?
< radio buttons >
Yes < show Q6a >
No
 
Q6a
Month
< date input >
Year
< date input >

Give details
< text input - short answer >

Circumstances
Give any circumstances you want to be taken into account when we consider your application
< text input - short answer >

Remove
< button >

Add another
< button >

Q7 Have you ever enter into an Individual Voluntary Arrangement (IVA)?
< radio buttons >
Yes < show Q6a >
No
 
Q8 Have you ever been sued in relation to any debt?
< radio buttons >
Yes < show Q6a >
No

Q9 Have you ever been a director of a company that has become insolvent?
< radio buttons >
Yes < show Q6a >
No
 
Q10 Have you or your company ever received a penalty for any VAT or tax assessments?
< radio buttons >
Yes < show Q6a >
No

Q11 Have you or your company ever been penalised for submitting a late VAT or tax return, including through a county court?
< radio buttons >
Yes < show Q6a >
No

Q12 Have you or your company ever had a finding of professional negligence against you?
< radio buttons >
Yes < show Q6a >
No

Q13 Have you or your company ever been involved in unfair or wrongful dismissal or discrimination or any other adverse civil proceedings against you?
< radio buttons >
Yes < show Q6a >
No

Q14 Have you or your company ever had a finding of professional misconduct against you?
< radio buttons >
Yes < show Q6a >
No

Q15 Have you or your company ever had a finding of inadequate professional service against you?
< radio buttons >
Yes < show Q6a >
No
 
Q16 Have you ever had any other type of complaint raised against you?
< radio buttons >
Yes < show Q6a >
No

Q17 Have you ever resigned, been asked to resign or been dismissed from employment or judicial office?
< radio buttons >
Yes < show Q6a >
No

Q18

Is there anything else that is relevant to your character that you haven't already told us?
For example, anything which might make a member of the public think you're unsuitable for this post 

< radio buttons >
Yes < show Q6a >
No

### Current investigations or proceedings

Q19 Are you involved in any current investigations?
< radio buttons >
Yes < show Q6a >
No

**Comment by JonSJAC** [comment]
Where an applicant needs to provide dates of an offence, to avoid lots of boxes with different dates, can we have one text box, with a placeholder asking:

Please provide details of:
Offence date
Conviction date (if applicable)
Sentence date (if applicable and different from conviction date)
These should be in the format MM/YYYY

**Comment by LaurieJohnston** [comment]
Are all these dates needed **at the point of application**?
It's easier for users to fill in separate date fields because they will recognise the pattern and not have to think about how to format the info.
Rather than saying if applicable etc we could make the fields optional

**Comment by LaurieJohnston** [comment]
Character headings for you @ollietreend 

Motoring offences Q1-4
Criminal offences Q5
Insolvency and debt Q6-9
VAT and tax Q10-11
Professional conduct Q12-18
