### ISSUE TITLE
Declarations

### ISSUE THREAD

**Issue by sme-JAC** [JudicialAppointmentsCommission/digital-platform#98]
### Q1 Are you related to, or known to any of the JAC Commissioners? 

- [x] Yes - if they choose yes Show Q1a & Q1b
- [x] No

#### Q1a Select all the Commissioners that apply

[check box candidate can pick multiple options, per the below]

- [x] Professor Lord Ajay Kakkar, Chairman
- [x] Lady Justice Rafferty, Vice Chairman 
- [x] Judge Mathu Asokan 
- [x] Her Honour Judge Anuja Dhir 
- [x] Emir Khan Feisal 
- [x] Jane Furniss CBE 
- [x] Andrew Kennon 
- [x] Sarah Lee 
- [x] Professor Noel Lloyd CBE 
- [x] Judge Fiona Monk 
- [x] Brie Stevens-Hoare 
- [x] Dame Valerie Strachan DCB 
- [x] His Honour Judge Phillip Sycamore
- [x] Sir Simon Wessely 
- [x] Dame Philippa Whipple DBE 

#### Q1b How do you know them?
{Text box - Long Answer 250 words max]

### Q2 Confidentiality

< must validate by ticking >

- [x] I undertake to maintain absolute confidentiality relating to all aspects of the selection process for this selection exercise.

- [x]  I progress in the exercise I undertake to ensure that any relevant materials provided to me as part of the selection process are kept secure and not shared with anyone else.

- [x]  I understand that the Judicial Appointments Commission will automatically refer any suspected breach of this agreement to the Bar Standards Board, the Solicitors Regulatory Authority, CILEx Regulation, Judicial Conduct Investigations Office or other relevant regulatory body to consider as a potential breach of my professional obligations, or as misconduct, and this could result in disciplinary action by my regulator.

- [x] I understand that the Judicial Appointments Commission takes very seriously the integrity of the selection process and any evidence that a candidate has breached this agreement might result in disqualification from this and future exercises.

**Comment by tatyree** [comment]
@NoraJAC  > I added 'As' to statement 2 in Confidentiality.  'As I progress...'.  It didn't make without it.
